#!/bin/bash

# Validates compose.cue against the official Compose specification and regenerates
# everything derived from it:
#
#   compose*.yaml      one per key under `files:` in compose.cue
#   .env.example       host-side variables, ready to `cp .env.example .env`
#   env-manifest.json  machine-readable inventory of every variable and its origin
#
# compose.cue and env.cue are the source of truth. Edits made directly to the
# generated files are lost on the next run — `cue export` emits no comments, so the
# banner is prepended here to say so in the files themselves.
#
# Requires the cue CLI: go install cuelang.org/go/cmd/cue@latest
#   (or `pacman -S cue` / see https://cue.dev/docs/introduction/installation/)

set -eE

cd "$(dirname "$0")"

if ! command -v cue > /dev/null; then
  echo "error: cue not found on PATH" >&2
  echo "       install with: go install cuelang.org/go/cmd/cue@latest" >&2
  echo "       (then add \$(go env GOPATH)/bin to PATH)" >&2
  exit 1
fi

# -c requires the result to be fully concrete, so an unresolved reference is an
# error here rather than a null that reaches Docker. This is also where the
# env-var drift guards in env.cue fire.
echo "Validating compose.cue..."
cue vet -c ./compose.cue ./env.cue

# Targets are discovered from the CUE rather than hardcoded, so commenting a file
# out of `files:` does not break this script — it just stops being generated.
mapfile -t TARGETS < <(cue export --out text \
  -e 'strings.Join([for k, _ in files {k}], "\n")' ./compose.cue ./env.cue)

if [ "${#TARGETS[@]}" -eq 0 ]; then
  echo "error: no files declared under \`files:\` in compose.cue" >&2
  exit 1
fi

banner() {
  echo "# Code generated by gen-compose.sh from compose.cue. DO NOT EDIT."
  echo "#"
  echo "# Edit compose.cue and re-run ./gen-compose.sh. That file carries the"
  echo "# documentation for every setting; cue export cannot emit comments."
}

for target in "${TARGETS[@]}"; do
  echo "Generating ${target}..."
  {
    banner
    cue export --out yaml -e "files.\"${target}\"" ./compose.cue ./env.cue
  } > "${target}.tmp"
  mv "${target}.tmp" "${target}"
done

# Host-side variables, for `cp .env.example .env`. The banner is already part of
# the generated text (env.cue builds it), so it is not prepended here.
echo "Generating .env.example..."
cue export --out text -e envExample ./compose.cue ./env.cue > .env.example.tmp
mv .env.example.tmp .env.example

# Machine-readable inventory. JSON takes no comments, so the provenance lives in
# the `source` and `project` fields instead.
echo "Generating env-manifest.json..."
cue export --out json -e envManifest ./compose.cue ./env.cue > env-manifest.json.tmp
mv env-manifest.json.tmp env-manifest.json

# Generated compose files left behind by a key that was removed from `files:`
# would still be picked up by `docker compose -f`, so say so rather than
# silently leaving a stale file that no longer matches compose.cue.
for stale in compose*.yaml; do
  [ -e "$stale" ] || continue
  found=0
  for target in "${TARGETS[@]}"; do
    [ "$stale" = "$target" ] && found=1
  done
  if [ "$found" -eq 0 ]; then
    echo "warning: ${stale} is no longer declared in compose.cue — delete it or restore the key" >&2
  fi
done

echo "Done."
